<?php

namespace Database\Factories;

use App\Models\Tag;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Factory for creating Tag test data.
 *
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Tag>
 */
class TagFactory extends Factory
{
    protected $model = Tag::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => $this->faker->unique()->word(),
            // slug will be auto-generated by the model
            'usage_count' => 0,
        ];
    }

    /**
     * Create a tag with a specific usage count.
     */
    public function withUsageCount(int $count): static
    {
        return $this->state(fn (array $attributes) => [
            'usage_count' => $count,
        ]);
    }

    /**
     * Create a popular tag (usage_count >= 10).
     */
    public function popular(): static
    {
        return $this->state(fn (array $attributes) => [
            'usage_count' => $this->faker->numberBetween(10, 100),
        ]);
    }

    /**
     * Create an unpopular tag (usage_count < 10).
     */
    public function unpopular(): static
    {
        return $this->state(fn (array $attributes) => [
            'usage_count' => $this->faker->numberBetween(0, 9),
        ]);
    }

    /**
     * Create a tag with a specific name.
     */
    public function withName(string $name): static
    {
        return $this->state(fn (array $attributes) => [
            'name' => $name,
        ]);
    }

    /**
     * Create a tag for travel categories.
     */
    public function travelCategory(): static
    {
        $categories = [
            'Beach', 'Mountain', 'City', 'Rural', 'Adventure',
            'Relaxation', 'Culture', 'Food', 'Shopping', 'Nature',
            'Family', 'Solo', 'Couple', 'Budget', 'Luxury'
        ];

        return $this->state(fn (array $attributes) => [
            'name' => $this->faker->randomElement($categories),
        ]);
    }

    /**
     * Create a tag for Korean destinations.
     */
    public function koreanDestination(): static
    {
        $destinations = [
            'Seoul', 'Busan', 'Jeju', 'Gyeongju', 'Gangneung',
            'Jeonju', 'Incheon', 'Daegu', 'Sokcho', 'Yeosu'
        ];

        return $this->state(fn (array $attributes) => [
            'name' => $this->faker->randomElement($destinations),
        ]);
    }
}
